### PR TITLE
Test Summary Report - Beautified

### PR DESCRIPTION
**Pull request by surevs**
- Report Helper.py file has been updated 
- Browser which is launched for displaying summary is maxmimised
- Necessary CSS has been updated into style sheet.py

### CODE REVIEW

**Comment by surevs** [comment]
Conflicts and minor over writes have been updated as necessary. Please update in case of any further changes needed

**Comment by surevs** [comment]
Flake8 errors have been fixed and ready for the merge!

**Comment by mdmintz** [comment]
I'm looking at the result of your styling changes for the report, and besides some alignment issues seen with it, I like the original style better. Also, the main logo for SeleniumBase is built around the original styling for the report, so I must keep that as is.

screen shot 2017-03-17 at 3 30 46 pm

**Comment by mdmintz** [comment]
For comparison, here's the original styling:

screen shot 2017-03-17 at 7 10 02 pm

**Comment by surevs** [comment]
Closing this request to keep the original report as it is

**Pull request closed without merging**
