### PR TITLE
Updated Readme

### PR DESCRIPTION
**Pull request by surevs**
This is a commonly faced challenge due to system admin rights and being unable to edit the system variables for python setup, This tweak helps user to install all the necessary packages and proceed to roll

### CODE REVIEW

**Comment by surevs** [comment]
hello @mdmintz , please advise in case of any specific instructions like increase in build/release number etc. you might advise for pull requests.

Thanks so much,  Revant

**Comment by mdmintz** [comment]
@surevs Are you able to create a branch directly from my version of SeleniumBase, or only from your fork of it? I want to be able to git checkout the code and run it and see how it is. Looks mostly good... there are some minor changes that may be needed. If not, can you make it so that merging the pull request puts it somewhere other than master (another branch of SeleniumBase), that way I can make the final touches, and get the versioning synced so that the pypi version goes out at the same time it's merged into master.

**Comment by mdmintz** [comment]
I left you more info on Gitter chat. We can set up a Skype call and walk through details of getting this merged.

**Comment by surevs** [comment]
I have tried to create a branch in this repository. It says 
image

**Pull request merged**
