### PR TITLE
locale_code should set lang instead of just intl.accept_languages

### PR DESCRIPTION
**Pull request by jimmy927**
locale_code should set lang instead of just intl.accept_languages

### CODE REVIEW

**Comment by mdmintz** [comment]
Both https://stackoverflow.com/a/11375463/7058266 and https://stackoverflow.com/a/55254431/7058266 say that using `intl.accept_languages` is the correct way to do it. I see no effect with the `--lang` arg. Can you show me a full example where adding the arg changed website behavior with SeleniumBase?

**Comment by jimmy927** [comment]
> Both https://stackoverflow.com/a/11375463/7058266 and https://stackoverflow.com/a/55254431/7058266 say that using `intl.accept_languages` is the correct way to do it. I see no effect with the `--lang` arg. Can you show me a full example where adding the arg changed website behavior with SeleniumBase?


My code:

`Driver(lang="en_us")
`

With my patch i get english, without my patch i get swedish (which is the locale of the local windows)
Maybe this is different on different os ?

Chrome 130, Windows 10

**Comment by mdmintz** [comment]
I need to see a full example script, with a real website. Not partial code.

**Comment by jimmy927** [comment]
sorry, no time.
Just throw it away if you like.

**Pull request closed without merging**
