### PR TITLE
fixed: port exhaustion, snow_case

### PR DESCRIPTION
**Pull request by ManiMozaffar**
Hey!

1. You were using some import in middle of modules, any reason you've done that? like requests module.
2. There was a connection leak, due to GC not collecting TCPs. so let's just delete the TCP object, when we're done with the browser. Also It's better to just get rid of the TCP and free port, rather than letting GC to do it. The less we depend on GC, the more efficient and performant it can be. 
3. Thanks for refactoring uc's code :)  it was much easier to read, however, FileNotFoundError exception in patcher would never been caught in refactor.py again, because:
```python
class FileNotFoundError(OSError): ...
```
4. There were some snow_case naming, like using 1 length variable, so I decided to fix them as I was fixing this. Makes code much easier to understand.
5. You put headless=False, but then you didn't used it at all, any reason?
6. Better to write `return None` than just return, because after all zen's saying:
```
explicit is better than implicit
```

### CODE REVIEW

**Comment by ManiMozaffar** [comment]
@mdmintz I fixed the issue myself,
in this case, it was a circular reference, that was timelined based. we had to await for the listener to quit, then close the driver, rather than first closing the driver then closing the listener.

**Comment by ManiMozaffar** [comment]
> I heard recently from this thread: [ultrafunkamsterdam/undetected-chromedriver#1270 (comment)](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1270#issuecomment-1556371743) that the maintainer of Undetected Chromedriver is rewriting the whole package.
> 
> New_UC_Coming
> SeleniumBase's UC Mode is based on that, and so I try to keep it fairly consistent so that making changes is easier when they push changes. There are some notable differences that aren't directly related to browser detection, such as automatically downloading the correct version of Chromedriver needed, and sharing the same driver for all sessions, even when using multiple processes.
> 
> I noticed a similar PR by you in Undetected Chromedriver's repo, [ultrafunkamsterdam/undetected-chromedriver#1258](https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/1258), which hasn't been merged by the maintainer, likely due to the major rewrite coming. Therefore, this PR won't be merged either.
> 
> I can still answer some of your questions. Eg. 1. There are some imports in the middle of the code because I often do that if there's a chance that an import won't be used (via `if` statements, etc). Fewer imports usually means faster runtimes. For 2, I haven't seen these connection leaks. Maybe already covered by code changes. I would need to see details of how to reproduce the issue before trying to address it. For 3, that one seems valid, but SeleniumBase's code is just matching UC's code for consistency. And that UC path wouldn't be reached if using SeleniumBase anyway because there would always be a `self._custom_exe_path` in SB's case. For 4, I'm just maintaining consistency with UC. That's how they named their variables, so if they make changes, it'll be easier for me to adjust the SB UC code to match. For 5, that's still there for backwards compatibility. If someone tries to call the SB UC code with that arg, there won't be an error. For 6, that's a personal preference. If a method isn't expected to return anything, then a simple `return` works like a `return None`.
> 
> Reviewing PRs can be very time-consuming, as you can see. That's why I'm thinking of adopting the policy set here: https://github.com/readme/featured/how-open-is-open-source (`“Open-Source, not Open-Contribution”`, because dealing with even small code contributions can be too time-consuming.) People are still welcome to open well-documented issues and start discussions.

Alright then,
the issue regarding port leak happens in only windows, not in linux.
when opening an event loop in a thread in windows, it opens 2 port. if you don't close the event loop, it'll remain as opened. so these 2s pile up on each other until taking all the available port on the system. this issue had me in trouble for while, I had to restart the process when there was more than 50k port so that those are opened by the program gets closed.
for the port exhaustion to happen, you actually need to open 30k chrome in a process, so it's rare to happen.

```py
def run(self):
        try:
            asyncio.set_event_loop(self.loop)
            self.loop.run_until_complete(self.listen())
        except Exception as e:
            logger.warning("Reactor.run() => %s", e)
            # Add this -->
        finally:
            self.loop.close()

```

**Comment by mdmintz** [comment]
@ManiMozaffar Does it happen for you with either https://github.com/seleniumbase/SeleniumBase/blob/master/examples/uc_cdp_events.py OR https://github.com/seleniumbase/SeleniumBase/blob/master/examples/verify_undetected.py ?
Even multithreaded tests with SeleniumBase reuse the driver for all tests.

**Comment by ManiMozaffar** [comment]
> @ManiMozaffar Does it happen for you with either https://github.com/seleniumbase/SeleniumBase/blob/master/examples/uc_cdp_events.py OR https://github.com/seleniumbase/SeleniumBase/blob/master/examples/verify_undetected.py ? Even multithreaded tests with SeleniumBase reuse the driver for all tests.

As long as you're enabling CDP event it happens. 
this has nothing to do with driver.
The port exhaustion happens generally with this code as well:


it's the poor implementation of CDP listener, where the self.loop, which is async event loop is not closed.
Try this code:

```python
import threading
import asyncio
import os

import psutil


def check_connections():
    """Check count of ESTABLISHED connections."""
    return len([
        conn for conn in psutil.net_connections()
        if conn.status == 'ESTABLISHED' and conn.pid == os.getpid()
    ])


class CustomThread(threading.Thread):
    def __init__(self):
        self.event = threading.Event()
        self.loop = asyncio.new_event_loop()
        self.event.set()
        print(check_connections()) # always >  0


for _ in range(0, 100):
    CustomThread()
```


by default, python re-uses the ports opened by new_event_loop, but when you open an async event loop in each thread, then python opens 2 new ports rather than using the old ones.

but when you add self.loop.close (which you close the event loop that was opened), then it closes the ports that was opened by async event loop, so the bellow code doesn't have port exhaustion


```python
import threading
import asyncio
import os

import psutil


def check_connections():
    """Check count of ESTABLISHED connections."""
    return len([
        conn for conn in psutil.net_connections()
        if conn.status == 'ESTABLISHED' and conn.pid == os.getpid()
    ])


class CustomThread(threading.Thread):
    def __init__(self):
        self.event = threading.Event()
        self.loop = asyncio.new_event_loop()
        self.event.set()
        self.loop.close()
        print(check_connections()) # always == 0 
    
for _ in range(0, 100):
    CustomThread()
```


Well, to be honest it took me days until finding the root of problem :( 
The maintainer said that he wants to stop using driver, well that's a good news but that has nothing to do with this issue.
so idk, maybe I can open open a new PR, and just adjust this code, if that's okay to you? 
and add tests with github windows runner to check this won't happen in future?

**Comment by mdmintz** [comment]
@ManiMozaffar Hold. The UC maintainer is doing a full rewrite, so probably won't have any SB UC changes until that's ready.
As for the port issue, there won't any changes to that until I can see some SB sample code that reproduces the issue. I need to see some proof that SB UC code can run into the issue.

**Comment by ultrafunkamsterdam** [comment]
> I heard recently from this thread: [ultrafunkamsterdam/undetected-chromedriver#1270 (comment)](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1270#issuecomment-1556371743) that the maintainer of Undetected Chromedriver is rewriting the whole package.
> 
> New_UC_Coming
> SeleniumBase's UC Mode is based on that, and so I try to keep it fairly consistent so that making changes is easier when they push changes. There are some notable differences that aren't directly related to browser detection, such as automatically downloading the correct version of Chromedriver needed, and sharing the same driver for all sessions, even when using multiple processes.
> 
> I noticed a similar PR by you in Undetected Chromedriver's repo, [ultrafunkamsterdam/undetected-chromedriver#1258](https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/1258), which hasn't been merged by the maintainer, likely due to the major rewrite coming. Therefore, this PR won't be merged either.
> 
> I can still answer some of your questions. Eg. 1. There are some imports in the middle of the code because I often do that if there's a chance that an import won't be used (via `if` statements, etc). Fewer imports usually means faster runtimes. For 2, I haven't seen these connection leaks. Maybe already covered by code changes. I would need to see details of how to reproduce the issue before trying to address it. For 3, that one seems valid, but SeleniumBase's code is just matching UC's code for consistency. And that UC path wouldn't be reached if using SeleniumBase anyway because there would always be a `self._custom_exe_path` in SB's case. For 4, I'm just maintaining consistency with UC. That's how they named their variables, so if they make changes, it'll be easier for me to adjust the SB UC code to match. For 5, that's still there for backwards compatibility. If someone tries to call the SB UC code with that arg, there won't be an error. For 6, that's a personal preference. If a method isn't expected to return anything, then a simple `return` works like a `return None`.
> 
> Reviewing PRs can be very time-consuming, as you can see. That's why I'm thinking of adopting the policy set here: https://github.com/readme/featured/how-open-is-open-source (`“Open-Source, not Open-Contribution”`, because dealing with even small code contributions can be too time-consuming.) People are still welcome to open well-documented issues and start discussions.

I will not replace the package, just adding  a package.

**Pull request closed without merging**
