### PR TITLE
Fix issue with setting user_data_dir in --uc mode

### PR DESCRIPTION
**Pull request by mdmintz**
## Fix issue with setting ``user_data_dir`` in ``--uc`` mode
* https://github.com/seleniumbase/SeleniumBase/commit/a29101cbb0d9aeb80923a643761869d5896a9ac3
* This resolves https://github.com/seleniumbase/SeleniumBase/issues/1867

### CODE REVIEW

**Comment by anovob** [comment]
Still not create user data directory in my selected path.

**Comment by mdmintz** [comment]
Note that the profile-directory is already included when setting the user_data_dir, and so you probably just want to set ``user_data_dir`` without ``profile-directory`` in the ``chromium_arg``. If you're using PyInstaller, that's an issue on their end.

**Comment by anovob** [comment]
Yes I am using pyinstaller.

**Comment by mdmintz** [comment]
It's an issue with ``PyInstaller``. You may be able to work around it by making sure there are no spaces in the path where you run ``pytest``.

**Comment by anovob** [comment]
> Note that the profile-directory is already included when setting the user_data_dir, and so you probably just want to set `user_data_dir` without `profile-directory` in the `chromium_arg`. If you're using PyInstaller, that's an issue on their end.

Sir, I  set `user_data_dir` without `profile-directory` in the `chromium_arg` and try run python script without pyinstaller. Still not create user_data_dir in my selected path.

**Comment by mdmintz** [comment]
This is working for me when run with ``python``:

```python
from pprint import pformat
from seleniumbase import BaseCase

if __name__ == "__main__":
    from pytest import main
    main([__file__, "--uc", "--uc-cdp", "-s", '--user_data_dir=my_udd'])

class CDPTests(BaseCase):
    def test_display_cdp_events(self):
        if not self.undetectable or not self.uc_cdp_events:
            self.get_new_driver(undetectable=True, uc_cdp_events=True)
        self.driver.add_cdp_listener(
            "Network.requestWillBeSentExtraInfo",
            lambda data: print(pformat(data))
        )
        self.open("https://nowsecure.nl/#relax")
        self.assert_text("OH YEAH, you passed!", "h1", timeout=7.25)
        self.sleep(2)
```

It correctly created ``my_udd`` in the folder where I ran ``python``.

**Comment by anovob** [comment]
```
import pathlib
import time
from seleniumbase import Driver

project_dir = pathlib.Path().absolute()
user_data_path = str(project_dir / 'userdatas' / f"userdata")
driver =  Driver(user_data_dir=user_data_path, uc=True)
driver.get('https://nowsecure.nl')
time.sleap(10)
driver.quit()
```
I try this. But not working.

**Comment by anovob** [comment]
I want to run multiple browser with separate `user_data_dir`. But first browser create data directory then other browser can not create directory folder.

**Pull request merged**
